name: lazy_loc
description: "LazyLoc is a lightweight localization package for Flutter that automates translation file management and provides a simple `.tr()` extension for string translation."
version: 0.0.4
homepage: https://topmoveright.github.io/lazy_loc
repository: https://github.com/topmoveright/lazy_loc
issue_tracker: https://github.com/topmoveright/lazy_loc/issues
documentation: https://topmoveright.github.io/lazy_loc

topics:
  - i18n
  - l10n
  - localization
  - internationalization
  - translation

screenshots:
  - description: The LazyLoc logo.
    path: resources/logo.png

environment:
  sdk: ^3.10.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  args: ^2.4.2
  glob: ^2.1.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
